---
- name: Initialize New Raspberry Pi
  hosts: uninitialized_raspberries
  vars_files:
    - vars.yml
  become: yes
  become_method: sudo
  tasks:
    - name: Change Hostname
      hostname:
        name: "{{new_hostname}}"
        use: debian
    - name: Update Hosts File
      replace:
        path: /etc/hosts
        regexp: "raspberrypi$"
        replace: "{{new_hostname}}"
    - name: Restart mDNS Service
      systemd:
        state: restarted
        name: avahi-daemon
    - name: Ensure the en_US.UTF-8 Locale Exists
      locale_gen:
        name: en_US.UTF-8
        state: present
